let position = 0
let farbe = neopixel.rgb(255, 82, 0)
let strip = neopixel.create(HiwonderPins.P2, 50, PowerSource.Extern)
strip.setBrightness(40)
strip.showColor(farbe)
strip.show()
basic.forever(function () {
    position = randint(0, strip.length())
    strip.setBrightness(255)
    strip.setPixelColorRange(position, neopixel.colors(NeoPixelColors.White), 1)
    strip.show()
    basic.pause(100)
    strip.setBrightness(30)
    strip.setPixelColorRange(position, farbe, 1)
    strip.show()
})
basic.forever(function () {
    position = randint(0, strip.length())
    strip.setBrightness(102)
    strip.setPixelColorRange(position, neopixel.colors(NeoPixelColors.White), 1)
    strip.show()
    basic.pause(200)
    strip.setBrightness(30)
    strip.setPixelColorRange(position, farbe, 1)
    strip.show()
})
basic.forever(function () {
    position = randint(0, strip.length())
    strip.setBrightness(255)
    strip.setPixelColorRange(position, neopixel.colors(NeoPixelColors.White), 1)
    strip.show()
    basic.pause(100)
    strip.setBrightness(30)
    strip.setPixelColorRange(position, farbe, 1)
    strip.show()
})
basic.forever(function () {
    position = randint(0, strip.length())
    strip.setBrightness(255)
    strip.setPixelColorRange(position, neopixel.colors(NeoPixelColors.White), 1)
    strip.show()
    basic.pause(100)
    strip.setBrightness(30)
    strip.setPixelColorRange(position, farbe, 1)
    strip.show()
})
basic.forever(function () {
    position = randint(0, strip.length())
    strip.setBrightness(30)
    strip.setPixelColorRange(position, farbe, 2)
    strip.show()
    basic.pause(40)
})
